DATA CLEANING (HANDLING MISSING AND INVALID DATA)

In [2]:
#import numpy as py
import numpy as np

#import pandas as pd
import pandas as pd

#import matplotlib as plt
import matplotlib.pyplot as plt

In [3]:
#check the current working directory
import os
print(os.getcwd())

c:\Users\Praise\Desktop\jupy notebook

IMPORT DATA

In [26]:
#read csv file
employees_info = pd.read_csv('PRACTICE DATASETS/messy_data.txt')
employees_info
#set the name column to be the index
#employees_info.set_index('Name', inplace=True)
employees_info

,Name,Age,Email,JoinDate,Salary,Country,Notes
0,Alice,25,alice@@gmail.com,2021/01/15,50000,USA,"Good, but sometimes late"
1,Bob,thirty,bob@gmail,15-02-2020,not available,United States,NaN
2,NaN,42,carol@company.com,2020-03-01,70000,US,NaN
3,David,29,david@company,2021-13-01,60000,UK,Missing salary info
4,Eve,22,eve@gmail.com,2020-05-20,55000,United Kingdom,NaN
5,Frank,,frank@@mail.com,2019-11-31,48000,UK,NaN
6,Grace,27,grace@mail.com,2021-07-10,NaN,England,NaN
7,Helen,35,helen@company.com,2020-02-30,65000,UK,NaN
8,Ian,28,ian@@gmail.com,2021-06-15,52000,United States,NaN
9,Julia,31,julia@gmail.com,2020-08-25,not disclosed,UK,NaN

In [27]:
#perform descriptive statistics on the dataframe
employees_info.describe()
employees_info.info()
#employees_info['Salary'].mean()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      9 non-null      object
 1    Age      10 non-null     object
 2   Email     10 non-null     object
 3   JoinDate  10 non-null     object
 4   Salary    9 non-null      object
 5   Country   10 non-null     object
 6   Notes     2 non-null      object
dtypes: object(7)
memory usage: 692.0+ bytes

DATA CLEANING

In [28]:
# Remove leading/trailing spaces from all column names
employees_info.columns = employees_info.columns.str.strip()
employees_info
#check column names
print(employees_info.columns)

Index(['Name', 'Age', 'Email', 'JoinDate', 'Salary', 'Country', 'Notes'], dtype='object')

In [45]:
#finding missing values
employees_info.isnull()
#dropping empty and invalid columns(notes and join date)
employees_info.drop('JoinDate', axis=1, inplace=True)
employees_info

    Name  Age            Email  Salary         Country
0  Alice   25  alice@gmail.com   50000   United States
1    Bob   29        bob@gmail   57142   United States
2    NaN   42  carol@gmail.com   70000   United States
3  David   29  david@gmail.com   60000  United Kingdom
4    Eve   22    eve@gmail.com   55000  United Kingdom
5  Frank   29  frank@gmail.com   48000  United Kingdom
6  Grace   27  grace@gmail.com   57142  United Kingdom
7  Helen   35  helen@gmail.com   65000  United Kingdom
8    Ian   28    ian@gmail.com   52000   United States
9  Julia   31  julia@gmail.com   57142  United Kingdom

In [ ]:
#standardising country names
employees_info['Country'].replace({
    'USA': 'United States',
    'US': 'United States',
    'United States': 'United States',
    'UK': 'United Kingdom',
    'England': 'United Kingdom',
    'United Kingdom': 'United Kingdom'
}, inplace=True)
employees_info

C:\Users\Praise\AppData\Local\Temp\ipykernel_19920\2514848012.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  employees_info['Country'].replace({

    Name     Age              Email    JoinDate         Salary         Country
0  Alice      25   alice@@gmail.com  2021/01/15          50000   United States
1    Bob  thirty          bob@gmail  15-02-2020  not available   United States
2    NaN      42  carol@company.com  2020-03-01          70000   United States
3  David      29      david@company  2021-13-01          60000  United Kingdom
4    Eve      22      eve@gmail.com  2020-05-20          55000  United Kingdom
5  Frank            frank@@mail.com  2019-11-31          48000  United Kingdom
6  Grace      27     grace@mail.com  2021-07-10            NaN  United Kingdom
7  Helen      35  helen@company.com  2020-02-30          65000  United Kingdom
8    Ian      28     ian@@gmail.com  2021-06-15          52000   United States
9  Julia      31    julia@gmail.com  2020-08-25  not disclosed  United Kingdom

In [31]:
#convert the Salary and Age columns to numeric values
employees_info['Salary'] = pd.to_numeric(employees_info['Salary'], errors='coerce')
employees_info['Age'] = pd.to_numeric(employees_info['Age'], errors='coerce')
employees_info

    Name   Age              Email    JoinDate   Salary         Country
0  Alice  25.0   alice@@gmail.com  2021/01/15  50000.0   United States
1    Bob   NaN          bob@gmail  15-02-2020      NaN   United States
2    NaN  42.0  carol@company.com  2020-03-01  70000.0   United States
3  David  29.0      david@company  2021-13-01  60000.0  United Kingdom
4    Eve  22.0      eve@gmail.com  2020-05-20  55000.0  United Kingdom
5  Frank   NaN    frank@@mail.com  2019-11-31  48000.0  United Kingdom
6  Grace  27.0     grace@mail.com  2021-07-10      NaN  United Kingdom
7  Helen  35.0  helen@company.com  2020-02-30  65000.0  United Kingdom
8    Ian  28.0     ian@@gmail.com  2021-06-15  52000.0   United States
9  Julia  31.0    julia@gmail.com  2020-08-25      NaN  United Kingdom

In [32]:
#calculate the mean salary
avg_salary = employees_info['Salary'].mean()
avg_salary
#filling the missing values in the Salary column with the mean salary
employees_info.fillna({'Salary': avg_salary}, inplace=True)
employees_info

    Name   Age              Email    JoinDate        Salary         Country
0  Alice  25.0   alice@@gmail.com  2021/01/15  50000.000000   United States
1    Bob   NaN          bob@gmail  15-02-2020  57142.857143   United States
2    NaN  42.0  carol@company.com  2020-03-01  70000.000000   United States
3  David  29.0      david@company  2021-13-01  60000.000000  United Kingdom
4    Eve  22.0      eve@gmail.com  2020-05-20  55000.000000  United Kingdom
5  Frank   NaN    frank@@mail.com  2019-11-31  48000.000000  United Kingdom
6  Grace  27.0     grace@mail.com  2021-07-10  57142.857143  United Kingdom
7  Helen  35.0  helen@company.com  2020-02-30  65000.000000  United Kingdom
8    Ian  28.0     ian@@gmail.com  2021-06-15  52000.000000   United States
9  Julia  31.0    julia@gmail.com  2020-08-25  57142.857143  United Kingdom

In [33]:
#calculate the average age
avg_age = employees_info['Age'].mean()
avg_age
#filling the missing values in the Age column with the mean age
employees_info.fillna({'Age': avg_age}, inplace=True)
employees_info

    Name     Age              Email    JoinDate        Salary         Country
0  Alice  25.000   alice@@gmail.com  2021/01/15  50000.000000   United States
1    Bob  29.875          bob@gmail  15-02-2020  57142.857143   United States
2    NaN  42.000  carol@company.com  2020-03-01  70000.000000   United States
3  David  29.000      david@company  2021-13-01  60000.000000  United Kingdom
4    Eve  22.000      eve@gmail.com  2020-05-20  55000.000000  United Kingdom
5  Frank  29.875    frank@@mail.com  2019-11-31  48000.000000  United Kingdom
6  Grace  27.000     grace@mail.com  2021-07-10  57142.857143  United Kingdom
7  Helen  35.000  helen@company.com  2020-02-30  65000.000000  United Kingdom
8    Ian  28.000     ian@@gmail.com  2021-06-15  52000.000000   United States
9  Julia  31.000    julia@gmail.com  2020-08-25  57142.857143  United Kingdom

In [35]:
#clean the email addresses
# Fix double '@' and replace 'company.com' with 'gmail.com'
employees_info['Email'] = (
    employees_info['Email']
    .str.replace(r'@@', '@', regex=True)
    .str.replace(r'company\.com', 'gmail.com', regex=True)
    .str.replace(r'mail\.com', 'gmail.com', regex=True)
    .str.replace('company', 'gmail.com', regex=False)
    # Replace 'ggmail' or 'gggmail' with 'gmail'
    .str.replace(r'g+mail', 'gmail', regex=True)
)
employees_info

    Name  Age            Email    JoinDate  Salary         Country
0  Alice   25  alice@gmail.com  2021/01/15   50000   United States
1    Bob   29        bob@gmail  15-02-2020   57142   United States
2    NaN   42  carol@gmail.com  2020-03-01   70000   United States
3  David   29  david@gmail.com  2021-13-01   60000  United Kingdom
4    Eve   22    eve@gmail.com  2020-05-20   55000  United Kingdom
5  Frank   29  frank@gmail.com  2019-11-31   48000  United Kingdom
6  Grace   27  grace@gmail.com  2021-07-10   57142  United Kingdom
7  Helen   35  helen@gmail.com  2020-02-30   65000  United Kingdom
8    Ian   28    ian@gmail.com  2021-06-15   52000   United States
9  Julia   31  julia@gmail.com  2020-08-25   57142  United Kingdom

In [49]:
#filling the missing value in the name column with 'Unknown'
employees_info.fillna({'Name': 'Unknown'}, inplace=True)
#setting the index to be the name column
employees_info.set_index('Name', inplace=True)
employees_info

         Age            Email  Salary         Country
Name
Alice     25  alice@gmail.com   50000   United States
Bob       29        bob@gmail   57142   United States
Unknown   42  carol@gmail.com   70000   United States
David     29  david@gmail.com   60000  United Kingdom
Eve       22    eve@gmail.com   55000  United Kingdom
Frank     29  frank@gmail.com   48000  United Kingdom
Grace     27  grace@gmail.com   57142  United Kingdom
Helen     35  helen@gmail.com   65000  United Kingdom
Ian       28    ian@gmail.com   52000   United States
Julia     31  julia@gmail.com   57142  United Kingdom

In [50]:
#back up the final cleaned data
employees_info.to_csv('PRACTICE DATASETS/cleaned_employees_info.csv', index=False)